# Generated by Django 5.2.17 on 2026-09-18 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documenttype_available_to_alternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinstruction',
            name='url',
            field=models.URLField(blank=True, default='', validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на инструкцию'),
        ),
    ]
